### PR TITLE
CLI wallet guide

### PR DESCRIPTION
**Pull request by Satori-Nakamoto**

### CODE REVIEW

**Comment by Satori-Nakamoto** [comment]
Does this even need a license? I have no idea how to use github.

**Comment by cryptochangements34** [comment]
This section should be covered under the whole repo's license. It should not have its own "sub-license"

**Comment by Satori-Nakamoto** [comment]
Got it, thanks.

**Comment by cryptochangements34** [comment]
Because this is going to be displayed as a page on the website, it doesn't need a README

**Comment by Satori-Nakamoto** [comment]
Any other changes needed before it's ready to publish?

**Comment by cryptochangements34** [comment]
This will need to be put into a browser rendered format but I'll merge it in as is so that it's at least accessible for now

**Pull request merged**
